version: '3.8'
services:
  log-service1:
    image: dar34p3r/arep-taller-6:log-service
    ports:
      - "35001:35000"
  log-service2:
    image: dar34p3r/arep-taller-6:log-service
    ports:
      - "35002:35000"
  log-service3:
    image: dar34p3r/arep-taller-6:log-service
    ports:
      - "35003:35000"
  round-robin-service:
    image: round-robin
    ports:
      - "36000:36000"
  mongodb:
    image: dar34p3r/arep-taller-6:mongo
    ports:
      - "27017:27017"
